<a href="https://colab.research.google.com/github/DepartmentOfStatisticsPUE/air-2024/blob/main/notebooks/5_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Zadanie 1


In [3]:
np.array( [[1, 2],
           [3, 4]])

np.array( [(1, 2),
           (3, 4)])

array([[1, 2],
       [3, 4]])

In [9]:
A = np.array([[1, 2, -1, 0], [3, -2, 4, 5], [2, 6, 5, -3], [0, 1, 5, -4]])
B = np.array([[3, 6], [4, 0], [2, -1], [1, 1]])
A

array([[ 1,  2, -1,  0],
       [ 3, -2,  4,  5],
       [ 2,  6,  5, -3],
       [ 0,  1,  5, -4]])

In [10]:
np.linalg.det(A)

154.00000000000006

In [11]:
A @ B

array([[ 9,  7],
       [14, 19],
       [37,  4],
       [10, -9]])

In [13]:
np.matmul(A, B)

array([[ 9,  7],
       [14, 19],
       [37,  4],
       [10, -9]])

In [14]:
A.dot(B)

array([[ 9,  7],
       [14, 19],
       [37,  4],
       [10, -9]])

In [15]:
B @ A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)

In [12]:
A * A

array([[ 1,  4,  1,  0],
       [ 9,  4, 16, 25],
       [ 4, 36, 25,  9],
       [ 0,  1, 25, 16]])

In [16]:
B.T

array([[ 3,  4,  2,  1],
       [ 6,  0, -1,  1]])

In [17]:
B.transpose()

array([[ 3,  4,  2,  1],
       [ 6,  0, -1,  1]])

In [19]:
np.transpose(B) @ A ## B^T A

array([[19, 11, 28, 10],
       [ 4,  7, -6, -1]])

In [21]:
np.linalg.inv(A)
np.linalg.pinv(A)

array([[ 1.42207792,  0.2012987 , -0.51298701,  0.63636364],
       [-0.43506494, -0.08441558,  0.34415584, -0.36363636],
       [-0.44805195,  0.03246753,  0.17532468, -0.09090909],
       [-0.66883117,  0.01948052,  0.30519481, -0.45454545]])

In [23]:
np.round(np.linalg.inv(A) @ A)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0., -0.],
       [-0., -0.,  1., -0.],
       [ 0.,  0.,  0.,  1.]])

In [24]:
A @ A @ A

array([[ -15,   51,   38,  -98],
       [ 190,   94,  111,  261],
       [ 151,  241,  341, -109],
       [ 103,   38,  158,   69]])

In [26]:
np.linalg.matrix_power(A, 3)

array([[ -15,   51,   38,  -98],
       [ 190,   94,  111,  261],
       [ 151,  241,  341, -109],
       [ 103,   38,  158,   69]])

In [27]:
A**3
np.power(A, 3)

array([[  1,   8,  -1,   0],
       [ 27,  -8,  64, 125],
       [  8, 216, 125, -27],
       [  0,   1, 125, -64]])

Zadanie 2


In [35]:
A = np.array([[3, 1, -2], [-3,2,1], [-2,6,3]])
B = np.array([[1,2,-2], [0,2,-1]])
C = np.array([[1,2],[3,4]])

In [36]:
[np.linalg.det(A), np.linalg.det(C)]

[35.00000000000001, -2.0000000000000004]

In [37]:
A @ B.T

array([[ 9,  4],
       [-1,  3],
       [ 4,  9]])

In [38]:
C.T

array([[1, 3],
       [2, 4]])

In [40]:
np.linalg.inv(C)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [39]:
np.linalg.inv(A) @ B.T @ np.linalg.matrix_power(C,2)

array([[-23.        , -33.42857143],
       [  5.2       ,   7.54285714],
       [-35.4       , -51.37142857]])

In [47]:
dane = np.arange(1,10)
dane.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
A

array([[ 3,  1, -2],
       [-3,  2,  1],
       [-2,  6,  3]])

In [51]:
A[:, 0]
A[0, :]
A[[0,2], :]

array([[ 3,  1, -2],
       [-2,  6,  3]])

In [53]:
np.sum(A)
A.sum()

9

In [60]:
np.sum(A, axis=0) ## sumy w poszczególnych kolumnach

array([-2,  9,  2])

In [59]:
np.sum(A, axis=1) ## sumy w poszczególnych wierszach

array([2, 0, 7])

In [62]:
A[1,1] = -99
A

array([[  3,   1,  -2],
       [ -3, -99,   1],
       [ -2,   6,   3]])

In [66]:
np.zeros([5,5])
np.zeros([5,5], dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [67]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [68]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Zadanie 8

In [72]:
x = np.arange(1,11)
y = np.array([[10,15,13,22,23,20,18,25,27,22]])
x

array([[10, 15, 13, 22, 23, 20, 18, 25, 27, 22]])

In [79]:
np.shape(x) ## wymiar macierzy (wiersze, kolumny)
jedynki = np.ones(np.shape(x)[0]) ## może być też len(x)
jedynki

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [91]:
X = np.transpose( np.vstack((jedynki, x)) )
X

array([[ 1.,  1.],
       [ 1.,  2.],
       [ 1.,  3.],
       [ 1.,  4.],
       [ 1.,  5.],
       [ 1.,  6.],
       [ 1.,  7.],
       [ 1.,  8.],
       [ 1.,  9.],
       [ 1., 10.]])

$$
\beta = (X^TX)^{-1}X^TY
$$